// Authorized Meower
export const SET_AUTHORIZED_MEOWER = "SET_Authorized_MEOWER"

// Meows
export const RECEIVE_MEOWS = "RECEIVE_MEOWS"
export const ADD_MEOW = "ADD_MEOW"
export const SAVE_POLL_MEOW = "SAVE_POLL_MEOW"

// Meowers
export const RECEIVE_MEOWERS = "RECEIVE_MEOWERS"
export const ADD_MEOW_TO_AUTHORIZED_MEOWER = "ADD_MEOW_TO_AUTHORIZED_MEOWER"
export const SAVE_POLL_MEOW_TO_AUTHORIZED_MEOWER = "SAVE_POLL_MEOW_TO_AUTHORIZED_MEOWER"